name: EventCardMaker
options:
  bundleIdPrefix: com.fabrica
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

targets:
  EventCardMaker:
    type: application
    platform: iOS
    sources:
      - EventCardMaker
    settings:
      base:
        INFOPLIST_KEY_NSCameraUsageDescription: "カード作成のためにカメラを使用します"
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
